# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Splash Blog
browser_title:    Splash Blog
tagline:          'The official Splash Wars blog'
description:      'The official blog for Splash Wars, the splashiest car combat game.'
url:              https://blog.splashwars.io
baseurl:          https://blog.splashwars.io/
steam_link:       https://store.steampowered.com/app/989720/Splash_Wars/
discord_link:     https://invite.gg/splashwars

author:
  name:           'Feliciano Santana'
  url:            https://thenameisflic.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate, jekyll-gist]
